management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  app:
    name: Travel Agency
    description: This is Spring Boot Application
    version: 1.0.0
  java-vendor: ${java.specification.vendor}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_agency
    username: root
    password: 3707
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true